import ocFullJS from 'opencascade.js/dist/opencascade.full.js';
import {createSharedCore} from './shared-core-wasm.js';
import {browserGreedyMeta,stagedMillTurnBaseline} from './sequence-policy.mjs';

const palette={air:'#ffffff',target:'#087f8c',holding:'#526079',remove:'#f5a544',shadow:'#9d8ac7',reach:'#8dc9e8',stock:'#e8eef1',ink:'#183442',muted:'#5c7079',line:'#bccbd0'};
const progress=(phase,percent)=>postMessage({type:'progress',phase,percent});
const count=a=>a.reduce((s,v)=>s+(v?1:0),0);
const point=(origin,pitch,shape,i)=>{const yz=shape[1]*shape[2],x=Math.floor(i/yz),r=i%yz,y=Math.floor(r/shape[2]),z=r%shape[2];return origin.map((o,j)=>o+([x,y,z][j]+.5)*pitch);};
async function maskId(mask,pool){const packed=new Uint8Array(Math.ceil(mask.length/8));mask.forEach((v,i)=>{if(v)packed[i>>3]|=1<<(i&7);});const id=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',packed)),b=>b.toString(16).padStart(2,'0')).join('');if(!pool[id]){const bytes=[];for(let i=0;i<packed.length;){let j=i+1;while(j<packed.length&&packed[j]===packed[i])j++;let n=j-i;while(n>=128){bytes.push((n&127)|128);n>>=7;}bytes.push(n,packed[i]);i=j;}let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.slice(i,i+32768));pool[id]={codec:'packed-lsb-rle1',bytes:packed.length,data:btoa(binary)};}return id;}
function directions(){const rows=[];for(const x of [-1,0,1])for(const y of [-1,0,1])for(const z of [-1,0,1])if(x||y||z){const n=Math.hypot(x,y,z);rows.push({id:`mill_${x>=0?'+':''}${x}_${y>=0?'+':''}${y}_${z>=0?'+':''}${z}`,vector:[x/n,y/n,z/n]});}return rows;}

async function prepare(bytes,options){
 progress('Loading OpenCascade',2);const oc=await new ocFullJS({locateFile:name=>name.endsWith('.wasm')?new URL('./opencascade.full.wasm',self.location.href).href:name});
 oc.FS.writeFile('/upload.step',new Uint8Array(bytes));const reader=new oc.STEPControl_Reader_1(),range=new oc.Message_ProgressRange_1();let shape;
 try{const readStatus=reader.ReadFile('/upload.step'),done=oc.IFSelect_ReturnStatus?.IFSelect_RetDone??oc.IFSelect_RetDone,enumValue=value=>value?.value??value;if(enumValue(readStatus)!==enumValue(done))throw new Error(`OpenCascade could not read this STEP file (status ${JSON.stringify(readStatus)}, expected ${JSON.stringify(done)}).`);if(!reader.TransferRoots(range))throw new Error('The STEP file contains no transferable solid.');shape=reader.OneShape();}finally{range.delete();reader.delete();oc.FS.unlink('/upload.step');}
 const box=new oc.Bnd_Box_1();try{oc.BRepBndLib.AddOptimal(shape,box,false,false);const lo=box.CornerMin(),hi=box.CornerMax();let targetBounds;try{targetBounds=[[lo.X(),lo.Y(),lo.Z()],[hi.X(),hi.Y(),hi.Z()]];}finally{lo.delete();hi.delete();}
  const pitch=options.pitch,allowance=options.allowance,low=targetBounds[0].map(x=>Math.floor((x-allowance)/pitch)*pitch),high=targetBounds[1].map(x=>Math.ceil((x+allowance)/pitch)*pitch),dims=high.map((x,i)=>Math.round((x-low[i])/pitch)),cells=dims.reduce((a,b)=>a*b,1);if(cells>options.maximumCells)throw new Error(`The selected resolution creates ${cells.toLocaleString()} cells; the limit is ${options.maximumCells.toLocaleString()}.`);if(dims.some(x=>x<1))throw new Error('The imported model has invalid bounds.');
  progress('Classifying the STEP solid',8);const classifier=new oc.BRepClass3d_SolidClassifier_2(shape),target=new Uint8Array(cells),stock=new Uint8Array(cells),holding=new Uint8Array(cells);const axisIndex={X:0,Y:1,Z:2}[options.axis],axisOrigin=targetBounds[0].map((v,i)=>(v+targetBounds[1][i])/2),radial=[0,1,2].filter(i=>i!==axisIndex),radius=Math.hypot(...radial.map(i=>(targetBounds[1][i]-targetBounds[0][i])/2))+allowance;
  const enumValue=value=>value?.value??value,inState=oc.TopAbs_State?.TopAbs_IN??oc.TopAbs_IN,onState=oc.TopAbs_State?.TopAbs_ON??oc.TopAbs_ON;
  try{for(let i=0;i<cells;i++){const p=point(low,pitch,dims,i),gp=new oc.gp_Pnt_3(...p);try{classifier.Perform(gp,1e-7);const state=classifier.State();target[i]=enumValue(state)===enumValue(inState)||enumValue(state)===enumValue(onState)?1:0;}finally{gp.delete();}const r=Math.hypot(...radial.map(j=>p[j]-axisOrigin[j]));stock[i]=r<=radius+1e-9?1:0;const station=p[axisIndex],edge=options.held==='negative'?low[axisIndex]+options.holdingLength:high[axisIndex]-options.holdingLength;if(stock[i]&&(options.held==='negative'?station<=edge:station>=edge))holding[i]=1;if(i%(dims[1]*dims[2])===0)progress('Classifying the STEP solid',8+Math.round(48*i/cells));}}
  finally{classifier.delete();}
  const targetCount=count(target),stockCount=count(stock),holdingCount=count(holding),protectedMask=Uint8Array.from(target,(v,i)=>v|holding[i]),protectedCount=count(protectedMask),initialExcess=stockCount-protectedCount;
  if(!targetCount)throw new Error('No occupied target cells were found. Reduce the voxel pitch.');for(let i=0;i<cells;i++)if(target[i]&&!stock[i])throw new Error('The automatic stock does not contain the imported target.');
  progress('Computing mill-turn actions',58);const core=await createSharedCore(new URL('./',self.location.href)),masks={},sceneMasks={stock:await maskId(stock,masks),target:await maskId(target,masks),holding:await maskId(holding,masks)},lengths=options.lengths,modes={},coreSpec={shape:dims,pitch,origin:low,bounds:[low,high],axis:{origin:axisOrigin,direction:[0,1,2].map(i=>i===axisIndex?1:0),radius,held:options.held==='negative'?-1:1}},total=(directions().length+3)*lengths.length;let completed=0;
  for(const mode of ['turning','milling']){const defs=mode==='milling'?directions():['outside','face_positive','face_negative'].map(id=>({id,vector:null})),actions=[];for(const d of defs)for(const length of lengths){const available=!(mode==='turning'&&((d.id==='face_positive'&&options.held==='negative')||(d.id==='face_negative'&&options.held==='positive')));let remove,shadow,counts={remove:0,shadow:0,beyond:0};if(available){const row=core.classify(coreSpec,{stock,target,holding},mode,mode==='milling'?d.vector:d.id,length);counts=row.counts;remove=await maskId(Uint8Array.from(row.labels,x=>x===3),masks);shadow=await maskId(Uint8Array.from(row.labels,x=>x===4),masks);}const id=`${d.id}@${length}mm`,removed=counts.remove;actions.push({id,direction:d.id,vector:d.vector,length,label:d.id.replace(/^mill_/,'Direction ').replaceAll('_',' '),evaluation:{action_id:id,direction_id:d.id,length_mm:length,available,unavailable_reason:available?null:'held_end_facing',removed_voxels:removed,removed_mm3:removed*pitch**3,shadow_blocked_voxels:available?counts.shadow:null,shadow_blocked_mm3:available?counts.shadow*pitch**3:null,beyond_reach_voxels:available?counts.beyond:null,beyond_reach_mm3:available?counts.beyond*pitch**3:null,remaining_voxels:stockCount-removed,remaining_mm3:(stockCount-removed)*pitch**3,residual_excess_voxels:initialExcess-removed,residual_excess_mm3:(initialExcess-removed)*pitch**3,protected_voxels:protectedCount,target_voxels:targetCount,holding_voxels:holdingCount,reward:removed/Math.max(1,initialExcess),initial_excess_voxels:initialExcess,reference:{}},remove,shadow});completed++;progress('Computing mill-turn actions',58+Math.round(40*completed/total));}const actionAvailability=Object.fromEntries(actions.map(a=>[a.id,a.evaluation.available])),initial={mode,step_count:0,remaining_voxels:stockCount,remaining_volume_mm3:stockCount*pitch**3,residual_excess_voxels:initialExcess,residual_excess_mm3:initialExcess*pitch**3,cumulative_removed_voxels:0,cumulative_removed_mm3:0,terminated:initialExcess===0,truncated:false,terminal_reason:initialExcess===0?'excess_exhausted':'active',action_availability:actionAvailability};modes[mode]={actions,initial,example:[],example_meta:browserGreedyMeta};}
  const geometry={case_id:'uploaded',frame_id:'step_frame',origin_mm:low,pitch_mm:pitch,shape:dims,cell_volume_mm3:pitch**3,stock_bounds_mm:[low,high],axis:{origin_mm:axisOrigin,direction:coreSpec.axis.direction,frame_id:'step_frame'},held_side:options.held,stock_radius_mm:radius,radius_reference:'automatic_enclosing_cylinder',cad_volumes_mm3:{stock:null,target:null,holding:null},voxel_volumes_mm3:{stock:count(stock)*pitch**3,target:count(target)*pitch**3,holding:count(holding)*pitch**3},occupancy_method:'center_in_solid_from_browser_OCCT_point_classifier',qualification:'experimental_unqualified'};
  const workflow={kind:'mill_turn',default_process:'turning',processes:['turning','milling'],example:[],example_meta:{kind:'staged_greedy_geometric_baseline',source:'browser_generated',objective:'turning_then_milling'}};
  const result={schema:'shadow-gym-visual-data-1',model:'shared-cpp-core-1',qualified:false,maximumSteps:8,palette,masks,scenes:[{id:'uploaded',title:`Uploaded · ${options.name}`,geometry,lengths,masks:sceneMasks,modes,workflow,ui:{industrial:false,sectionAxis:axisIndex}}]};
  workflow.example=stagedMillTurnBaseline(result,result.scenes[0]);
  return result;
 }finally{box.delete();shape.delete();}}
self.onmessage=async event=>{if(event.data.type!=='prepare')return;try{const data=await prepare(event.data.bytes,event.data.options);postMessage({type:'complete',data});}catch(error){postMessage({type:'error',message:error?.message||String(error)});}};
